### ISSUE TITLE
panicked when show LunisolarDate for 2020-12-06

### ISSUE THREAD

**Issue by E834159672** [magiclen/chinese-lunisolar-calendar#1]
mycode 
```
use chinese_lunisolar_calendar::chrono::prelude::*;
use chinese_lunisolar_calendar::{ChineseVariant, LunisolarDate};


fn main() {

    let lunisolar_date = LunisolarDate::from_naive_date(NaiveDate::from_ymd(2020, 12, 6)).unwrap();

    println!("{}",lunisolar_date.to_chinese_string(ChineseVariant::Simple));
}

```

error:

```
[ra@ubuntu test-lunardate2]$ RUST_BACKTRACE=full cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/test-lunardate2`
thread 'main' panicked at 'attempt to subtract with overflow', /home/ra/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/chinese-lunisolar-calendar-0.1.14/src/lunar_year.rs:47:24
stack backtrace:
   0:     0x55cb37edf340 - std::backtrace_rs::backtrace::libunwind::trace::h72c2fb8038f1bbee
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x55cb37edf340 - std::backtrace_rs::backtrace::trace_unsynchronized::h1e3b084883f1e78c
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x55cb37edf340 - std::sys_common::backtrace::_print_fmt::h3bf6a7ebf7f0394a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:79
   3:     0x55cb37edf340 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2e8cb764b7fe02e7
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:58
   4:     0x55cb37ef7abc - core::fmt::write::h7a1184eaee6a8644
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1080
   5:     0x55cb37edd532 - std::io::Write::write_fmt::haeeb374d93a67eac
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/io/mod.rs:1516
   6:     0x55cb37ee146d - std::sys_common::backtrace::_print::h1d14a7f6ad632dc8
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:61
   7:     0x55cb37ee146d - std::sys_common::backtrace::print::h301abac8bb2e3e81
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:48
   8:     0x55cb37ee146d - std::panicking::default_hook::{{closure}}::hde0cb80358a6920a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:208
   9:     0x55cb37ee1118 - std::panicking::default_hook::h9b1a691049a0ec8f
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:227
  10:     0x55cb37ee1af1 - std::panicking::rust_panic_with_hook::h2bdec87b60580584
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:577
  11:     0x55cb37ee1699 - std::panicking::begin_panic_handler::{{closure}}::h101ca09d9df5db47
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484
  12:     0x55cb37edf7ac - std::sys_common::backtrace::__rust_end_short_backtrace::h3bb85654c20113ca
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153
  13:     0x55cb37ee1659 - rust_begin_unwind
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
  14:     0x55cb37ef6dd1 - core::panicking::panic_fmt::h48c31e1e3d550146
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
  15:     0x55cb37ef6d1d - core::panicking::panic::h184ede6dd822ffb4
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:50
  16:     0x55cb37ebeee6 - chinese_lunisolar_calendar::lunar_year::LunarYear::from_era::h78021992b46576c6
                               at /home/ra/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/chinese-lunisolar-calendar-0.1.14/src/lunar_year.rs:47
  17:     0x55cb37ebe328 - chinese_lunisolar_calendar::lunisolar_year::LunisolarYear::to_lunar_year::h5d9fba8c9f14fcd8
                               at /home/ra/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/chinese-lunisolar-calendar-0.1.14/src/lunisolar_year.rs:180
  18:     0x55cb37ebfe93 - chinese_lunisolar_calendar::lunisolar_date::LunisolarDate::write_to_chinese_string::h31347291961106db
                               at /home/ra/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/chinese-lunisolar-calendar-0.1.14/src/lunisolar_date.rs:406
  19:     0x55cb37ebfdb6 - chinese_lunisolar_calendar::lunisolar_date::LunisolarDate::to_chinese_string::hceaa99af2964b5f0
                               at /home/ra/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/chinese-lunisolar-calendar-0.1.14/src/lunisolar_date.rs:392
  20:     0x55cb37ebf045 - test_lunardate2::main::hf59dd78402add4fc
                               at /src/rust/test-lunardate2/src/main.rs:14
  21:     0x55cb37ebe53b - core::ops::function::FnOnce::call_once::heafbda881f3469cb
                               at /home/ra/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
  22:     0x55cb37ebf12e - std::sys_common::backtrace::__rust_begin_short_backtrace::h1a46b5d3199c8c93
                               at /home/ra/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:137
  23:     0x55cb37ebf721 - std::rt::lang_start::{{closure}}::h33bc1e9c7246e7e8
                               at /home/ra/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:66
  24:     0x55cb37ee1f17 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::he179d32a5d10d957
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:259
  25:     0x55cb37ee1f17 - std::panicking::try::do_call::hcb3d5e7be089b2b4
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:381
  26:     0x55cb37ee1f17 - std::panicking::try::h7ac93b0cd56fb701
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:345
  27:     0x55cb37ee1f17 - std::panic::catch_unwind::h7b40e396c93a4fcd
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panic.rs:382
  28:     0x55cb37ee1f17 - std::rt::lang_start_internal::h142b9cc66267fea1
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/rt.rs:51
  29:     0x55cb37ebf6f7 - std::rt::lang_start::hf502f24df0a95e3b
                               at /home/ra/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:65
  30:     0x55cb37ebf11a - main
  31:     0x7f2b210ef1e2 - __libc_start_main
  32:     0x55cb37ebe0ee - _start
  33:                0x0 - <unknown>
[ra@ubuntu test-lunardate2]$ 

``

**Comment by magiclen** [comment]
Thanks. It has been fixed. (8b94072743c81b7a00070a5b5a404bef15da2d35)

**Comment by E834159672** [comment]
it worked ,thanks
